name: 'Install pytorch and pytorch-geometric for CPU'
description: 'Installs a few common dependencies'
inputs:
  torch-verison:
    description: 'Version of pytorch to install'
    required: true
    default: '1.9.0'
  pyg-verison:
    description: 'Version of pytorch-geometric to install'
    required: true
    default: '2.0.1'
runs:
  using: "composite"
  steps:
    - name: "Install dependencies"
      run: |
        pip install --upgrade pip
        pip install wheel
        pip install torch==${{ inputs.torch-verison }}+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
        pip install torch-cluster==1.5.9 -f https://data.pyg.org/whl/torch-${{ inputs.torch-verison }}+cpu.html
        pip install torch-scatter==2.0.9 -f https://data.pyg.org/whl/torch-${{ inputs.torch-verison }}+cpu.html
        pip install torch-sparse==0.6.12 -f https://data.pyg.org/whl/torch-${{ inputs.torch-verison }}+cpu.html
        pip install torch-spline-conv==1.2.1 -f https://data.pyg.org/whl/torch-${{ inputs.torch-verison }}+cpu.html
        pip install torch-geometric==${{ inputs.pyg-verison }}
      shell: bash