path: /groups/icecube/petersen/GraphNetDatabaseRepository/Leon2022_DataAndMC_CSVandDB_StoppedMuons/last_one_lvl3MC.db
pulsemaps:
  - SRTInIcePulses
features:
  - dom_x
  - dom_y
  - dom_z
  - dom_time
  - charge
  - rde
  - pmt_area
truth:
  - energy
  - position_x
  - position_y
  - position_z
  - azimuth
  - zenith
  - pid
  - elasticity
  - sim_type
  - interaction_type
index_column: event_no
truth_table: truth
seed: 21
selection:
  test_nu_e: 20 random events ~ event_no % 5 == 0 & (pid == 12 | pid == -12)
  test_nu_mu: 20 random events ~ event_no % 5 == 0 & (pid == 14| pid == -14)
  test_nu_tau: 20 random events ~ event_no % 5 == 0 & (pid == 16 | pid == -16)
  test_mu: 20 random events ~ event_no % 5 == 0 & (pid == 13 | pid == -13)

  validation_nu_e: 20 random events ~ event_no % 5 == 1 & (pid == 12 | pid == -12)
  validation_nu_mu: 20 random events ~ event_no % 5 == 1 & (pid == 14 | pid == -14)
  validation_nu_tau: 20 random events ~ event_no % 5 == 1 & (pid == 16 | pid == -16)
  validation_mu: 20 random events ~ event_no % 5 == 1 & (pid == 13 | pid == -13)

  train_nu_e: 50 random events ~ event_no % 5 > 1 & (pid == 12 | pid == -12)
  train_nu_mu: 50 random events ~ event_no % 5 > 1 & (pid == 14 | pid == -14)
  train_nu_tau: 50 random events ~ event_no % 5 > 1 & (pid == 16 | pid == -16)
  train_mu: 50 random events ~ event_no % 5 > 1 & (pid == 13 | pid == -13)
